type: recipe
format_version: 1
maintainers: [dorotat]
logger: dllogger
labels:
  origin: bionemo
  workload_ref: ""
  bionemo_ci_pipeline_id: ""
  bionemo_commit_sha: ""
key_segments:
  domain: domain
  config_name: config
  warmup: warmup
  default_overwrites: False
  extra_overwrites: False
  seed: seed
  max_steps: msteps
  val_check_interval: valcheck
launchers:
  type:slurm:
    ntasks_per_node: '{gpus}'
  name:dgxa100_dracooci:
    mounts:
      /workspace/bionemo/models: /lustre/fsw/portfolios/convai/projects/convai_bionemo_training/jet/models
      /workspace/bionemo/data/: /lustre/fsw/portfolios/convai/projects/convai_bionemo_training/jet/data/openfold
spec:
  build: bionemo
  BIONEMO_HOME: "/workspace/bionemo"
  scope: ""
  platforms: [linux/amd64]
  NGC_CLI_FORMAT_TYPE: ascii
  NGC_CLI_ORG: nvidian
  NGC_CLI_TEAM: clara-lifesciences
  wandb_project_name: ""
  pipeline_label: ""
  warmup: 200
  default_overwrites: "++exp_manager.create_tensorboard_logger=True ++exp_manager.wandb_logger_kwargs.offline=False ++exp_manager.create_wandb_logger=True ++exp_manager.create_checkpoint_callback=False ++exp_manager.resume_if_exists=False"
  extra_overwrites: ""
  script: |-    
    cd {BIONEMO_HOME};
    if [ "$SLURM_LOCALID" = "0" ]; then bash examples/protein/openfold/scripts/install_third_party.sh; fi;
    export WANDB_API_KEY=$BIONEMO_WANDB_API_KEY;
    model_tag={model}__{variant}__{config_name};
    python examples/{domain}/{model}/{variant}.py --config-name {config_name} \
    trainer.num_nodes={nodes} trainer.devices={gpus} trainer.precision={precision} model.seed={seed} \
    trainer.max_steps={max_steps} model.num_train_iters={max_steps} model.micro_batch_size={batch_size} \
    trainer.val_check_interval={val_check_interval} \
    {default_overwrites} {extra_overwrites} \
    ++exp_manager.exp_dir={assets_dir} \
    ++exp_manager.wandb_logger_kwargs.project={wandb_project_name} \
    ++exp_manager.wandb_logger_kwargs.group=${{model_tag}} \
    ++exp_manager.wandb_logger_kwargs.job_type={pipeline_label} \
    ++exp_manager.wandb_logger_kwargs.name=${{model_tag}}__{precision}prec_{batch_size}bs_{nodes}node_{gpus}gpu_{max_steps}s_{val_check_interval}valcheck \
    ++create_dllogger_callbacks=True ++create_trainer_metric_callback=True \
    ++dllogger_callbacks_kwargs.use_existing_dllogger=True ++dllogger_callbacks_kwargs.warmup={warmup} \
    ++dllogger_callbacks_kwargs.json_file={dllogger_file} ++trainer_metric_callback_kwargs.log_path={assets_dir} \
    ++logs_dir={logs_dir}
  time_limit: 14400
  artifacts: {}
  metrics:
    train_loss_epoch:
      goal: minimize
      tags: [primary]
    val_loss:
      goal: minimize
      tags: [secondary]
products:
  - domain: [protein]
    variant: [train]
    model: [openfold]
    nodes: [2]
    gpus: [8]
    config_name: [openfold_initial_training]
    max_steps: [80000]
    batch_size: [1]
    precision: [32]
    seed: [44]
    val_check_interval: [50]


