type: recipe
format_version: 1
maintainers: [dorotat]
loggers: [tensorboard, dllogger, extra]
labels:
  origin: bionemo
  workload_ref: ""
  bionemo_ci_pipeline_id: ""
  bionemo_commit_sha: ""
key_segments:
  domain: domain
  config_name: config
  warmup: warmup
  default_overwrites: False
  extra_overwrites: False
  seed: seed
  max_steps: msteps
  dwnstr_task: dwnstrtask
  val_check_interval: valcheck
  accumulate_grad_batches: accgrad
launchers:
  type:slurm:
    ntasks_per_node: '{gpus}'
  name:dgxa100_dracooci:
    mounts:
      /workspace/bionemo/data: /lustre/fsw/portfolios/healthcareeng/projects/healthcareeng_bionemo/jet/data
spec:
  build: bionemo
  scope: ""
  BIONEMO_HOME: "/workspace/bionemo"
  platforms: [linux/amd64]
  wandb_project_name: ""
  wandb_run_link: ""
  pipeline_label: ""
  warmup: 200
  default_overwrites: "++exp_manager.create_tensorboard_logger=True ++exp_manager.wandb_logger_kwargs.offline=False ++exp_manager.create_wandb_logger=True ++exp_manager.create_checkpoint_callback=False ++exp_manager.resume_if_exists=False"
  extra_overwrites: ""
  script: |-
    cd {BIONEMO_HOME};
    mkdir -p {tensorboard_dir};
    export WANDB_API_KEY=$BIONEMO_WANDB_API_KEY;
    model_tag={model}_{variant}_{config_name}_{dwnstr_task}dwnstr;
    python examples/{domain}/{model}/{variant}.py --config-name {config_name} \
    trainer.num_nodes={nodes} trainer.devices={gpus} trainer.precision={precision} model.micro_batch_size={batch_size} \
    ++trainer.accumulate_grad_batches={accumulate_grad_batches} trainer.val_check_interval={val_check_interval} \
    ++model.optim.sched.constant_steps=null ++model.optim.sched.last_epoch=-1  ++model.optim.sched.min_lr=0.0000002 \
    ++model.optim.sched.anneal_percentage=0.10 ++model.optim.eps=10e-8  ++model.optim.weight_decay=0.01 \
    ++model.seed={seed} trainer.max_steps={max_steps} ++exp_manager.exp_dir={tensorboard_dir} \
    ++trainer.max_epochs=1 \
    ++model.dwnstr_task_validation.enabled={dwnstr_task} \
    ++model.data.index_mapping_dir={BIONEMO_HOME}/data/index_dir/{config_name} \
    ++model.data.dataset_path=/workspace/bionemo/data/uniref202104_esm2_120123_jm \
    {default_overwrites} {extra_overwrites}  \
    ++exp_manager.wandb_logger_kwargs.project={wandb_project_name} \
    ++exp_manager.wandb_logger_kwargs.group=${{model_tag}} \
    ++exp_manager.wandb_logger_kwargs.job_type={pipeline_label} \
    ++exp_manager.wandb_logger_kwargs.name=${{model_tag}}__{precision}prec_{batch_size}bs_{nodes}node_{gpus}gpu_{max_steps}s_{val_check_interval}valcheck_{accumulate_grad_batches}accgrad \
    ++create_trainer_metric_callback=True ++trainer_metric_callback_kwargs.log_path={assets_dir} \
    ++logs_dir={logs_dir}
  time_limit: 14400
  artifacts: {}
metrics:
  reduced_train_loss:
    goal: minimize
    tags: [accuracy]
    key: primary
  val_loss:
    goal: minimize
    tags: [accuracy ]
    key: secondary
  val_perplexity:
    goal: maximize
    tags: [ accuracy ]
    key: tertiary
  val_loss_ECE:
    goal: minimize
    tags: [ accuracy ]
    key: 4th
products:
  - nodes: [4]
    gpus: [8]
    precision: [32]
    products:
      - domain: [protein]
        dwnstr_task: [False]
        products:
          - variant: [pretrain]
            model: [esm2nv]
            config_name: [pretrain_esm2_650M]
            batch_size: [8]
            max_steps: [17000]
            seed: [1234]
            val_check_interval: [500]
            accumulate_grad_batches: [8]
tests_spec:
  - logic_type: static
    logic_spec:
      exit_codes:
        - 0
      baselines:
        consumed_samples:
          # (this should be exact)
          operator: eq
          value: 4341760.0
        val_loss:
          # mean +/- 5 * std
          operator: range
          max: 2.5305
          min: 2.4862
        reduced_train_loss:
          # mean +/- 5 * std
          operator: range
          max: 2.5316
          min: 2.4849
        grad_norm:
          # mean +/- 2 * std
          operator: range
          max: 0.8647
          min: 0.0 # sanity check
        val_perplexity:
          # mean +/- 5 * std
          operator: range
          max: 12.5577
          min: 12.0115
        val_loss_ECE:
          # mean +/- 5 * std
          operator: range
          max: 5.7773
          min: 5.6020
